# Generated by Django 5.0 on 2023-12-28 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamanagement', '0022_rename_oanda_account_id_admin_tinkoff_token_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='tinkoff_token',
        ),
    ]
